osx_image: xcode7.2
language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- gem install cocoapods
- pod install --project-directory=Pod

script: 
- xctool clean build -project Pod.xcworkspace -scheme SwiftSortsRelease
- xctool test -project Pod.xcworkspace -scheme SwiftSortsTests