osx_image: xcode8
language: objective-c

cache:
  directories:
  - Carthage

before_install:
- travis_wait 35; bin/bootstrap-if-needed

script:
- set -o pipefail && xcodebuild clean build -project Spots.xcodeproj -scheme "Spots-iOS" -sdk iphonesimulator
- set -o pipefail && xcodebuild test -project Spots.xcodeproj -scheme "Spots-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -enableCodeCoverage YES
- set -o pipefail && xcodebuild clean build -project Spots.xcodeproj -scheme "Spots-Mac" -sdk macosx
- set -o pipefail && xcodebuild test -project Spots.xcodeproj -scheme "Spots-Mac" -sdk macosx -enableCodeCoverage YES
- set -o pipefail && xcodebuild clean build -project Spots.xcodeproj -scheme "Spots-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0'
- set -o pipefail && xcodebuild test -project Spots.xcodeproj -scheme "Spots-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' -enableCodeCoverage YES

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
